### ISSUE TITLE
Ratpoison UI not showing up on top of game, when I alt tab to it its just a black screen.

### ISSUE THREAD

**Issue by mattbot101** [TheFuckingRat/RatPoison#131]
I tried changing the resolution, making it full screen windowed, running bat as admin, installing jdk again, adding java_home var, turning vsync on and off for the opengl layer, everything. Debug shows absolutely no errors. Tried from a fresh build of ratpoison as well. Validated CSGO itself, no fix. On 1.4.1. What should I try to make the UI show up? 

Edit: cmd prompt window output 
Finished loading settings
Launching...
[Debug] Looking for and initializing CSGO
[Debug] CSGO initialized
[Debug] Initializing scripts
[Debug] BHop, AutoStrafe, RCS initialized
[Debug] Recoil Crosshair, FlatAim, PathAim initialized
[Debug] SetAim, BoneTrigger, AutoKnife initialized
[Debug] ReducedFlash, SpectatorList, BombTimer initialized
[Debug] Initializing ESPs
[Debug] GlowEsp, IndicatorEsp, BoxEsp initialized
[Debug] SkeletonEsp, ChamsEsp, HitsoundEsp initialized
[Debug] RadarEsp initialized
[Debug] ESP, ESPToggle, Automatic Weapons initialized
[Debug] FastStop initialized
App Title: Counter-Strike: Global Offensive
[Debug] Updated viewports
Waiting for App
Initializing overlay
[Debug] Updated viewports

**Comment by TheFuckingRat** [comment]
Is this a new issue? When you alt tab is it just a black screen even if you hit the menu key? The menu should still pop up if it launches fine. See https://github.com/TheFuckingRat/RatPoison/issues/83 for additional troubleshooting that you may not have tried. Try running the .jar itself instead of the .bat. If the .jar works fine but the .bat doesn't your java_home is set incorrectly. If that's the case see https://github.com/TheFuckingRat/RatPoison/issues/128 delete the path line and that should fix it.

**Comment by mattbot101** [comment]
Running java -version gets me 
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) Client VM (build 25.221-b11, mixed mode)
I ran the .jar file and it now works fine, but the bat still doesn't work. Removing the path line also makes the UI black, when I alt tab I can see it in the list. Same problem. Should I just run the jar file? That works fine so far.

**Comment by TheFuckingRat** [comment]
Shouldnt be an issue running the jar instead, but I had the same issue with jdk 1.8 and use 12 now and it works fine, so I'd assume that's the issue even though removing the line didn't

**Comment by mattbot101** [comment]
I've reinstalled it twice now straight from the 12.0.2 exe file from [here](https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html) What else do I need to do to get it to 12.0.2?

**Comment by TheFuckingRat** [comment]
if java -version is still giving you 1.8 theres some path in your environment variables giving it the old one, edit your Path system variables and see if theres anything related to another java path, one that I had was something like ProgramFiles\Oracle\--whatever that would override java_home

**Comment by mattbot101** [comment]
Thanks, Ill check it out tomorrow.  For now I’ll close it.
