### ISSUE TITLE
When running Start RatPoison 1.3.4.bat, it's stuck on launching...

### ISSUE THREAD

**Issue by RaiyanAir** [TheFuckingRat/RatPoison#84]

**Comment by TheFuckingRat** [comment]
Only thing I can think of is it's still looking for CSGO, while the menu_app can be anything, it won't launch unless it finds CSGO, provide more information if this isn't the case

**Comment by RaiyanAir** [comment]
> Only thing I can think of is it's still looking for CSGO, while the menu_app can be anything, it won't launch unless it finds CSGO, provide more information if this isn't the case

I'm running it after I'm in game holding a weapon in hand. I just want to use glow esp and this is my menu settings:

MENU = false
MENU_APP = "Counter-Strike: Global Offensive"
OVERLAY_WIDTH = 800
OVERLAY_HEIGHT = 600

I play 4:3 fullscreen 800x600. 
Do you know a fix? I'm going to try your 13.2.2 from unknowncheats this time.

**Comment by TheFuckingRat** [comment]
I'm not the poster on UC, so using the versions there doesn't help me at all. Since menu is false, the only other output in the CMD should be 'App Title: Counter-Strike: Global Offensive' which isn't relevant and doesn't actually do anything since the Menu is off, and then 'Type help for options'. I would assume it gets stuck when initializing and trying to find csgo, is the window name in a different language, as in other than "Counter-Strike: Global Offensive" as it seems to be working fine for me. Providing all of your settings would help

**Comment by RaiyanAir** [comment]
The 13.2.2 didn't work either. I saw u change to JDK 12, so I downloaded that and rebuilt it. It's in english so the file name is csgo.exe and Name: Counter Strike: Global Offensive . These are the settings I used:

General.kts
------------
MENU = true
MENU_APP = "Counter-Strike: Global Offensive"
OVERLAY_WIDTH = 800
OVERLAY_HEIGHT = 600
WARNING = true
SPECTATOR_LIST = true
FAST_STOP = false
ENABLE_AIM = false

GlowESP.kts
------------
GLOW_ESP = true
INV_GLOW_ESP = false
MODEL_ESP = true
MODEL_AND_GLOW = false
GLOW_SHOW_TEAM = false
GLOW_SHOW_ENEMIES = true
GLOW_SHOW_BOMB = true
GLOW_SHOW_WEAPONS = false
GLOW_SHOW_GRENADES = false
GLOW_SHOW_TARGET = true

Scripts.kts
----------
ENABLE_BUNNY_HOP = false
ENABLE_RCS = false
ENABLE_RECOIL_CROSSHAIR = false
ENABLE_ESP = true
ENABLE_BONE_TRIGGER = false
AUTOMATIC_WEAPONS = false
ENABLE_REDUCED_FLASH = false
ENABLE_BOMB_TIMER = false

ALL_WEAPONS - ENABLE_PATH AIM and ENABLE_FLAT_AIM set to false
Everything else left as it is. 

It's still stuck in launching...

**Comment by TheFuckingRat** [comment]
@RaiyanAir Sorry for the delay, I pushed a hotfix that adds DEBUG to general.kts, enable it and launch ratpoison and comment what pops up in the cmd

**Comment by shoxie** [comment]
i think i have the same problem. the console prints this out :

Exception in thread "main" kotlin.KotlinNullPointerException
        at rat.poison.scripts.BoneTriggerKt.boneTrigger(BoneTrigger.kt:65)
        at rat.poison.RatPoison.main(RatPoison.kt:95)
        at rat.poison.RatPoison.main(RatPoison.kt)

**Comment by TheFuckingRat** [comment]
@shoxie Make sure you're on the most recent version, and that BONE_TRIGGER_SHOT_DELAY is a valid int (0 through X)

**Comment by RaiyanAir** [comment]
Hey I enabled debug and it says this: 
Finished loading settings
Launching...
[Debug] Looking for and initializing CSGO

**Comment by RaiyanAir** [comment]
I'm changing the overlay to match my game but it's still not woring ;(

**Comment by RaiyanAir** [comment]
I FIXED IT. THREAD CLOSED. My CSGO runs in administrator however the cheat wasn't running as admin so it was initailizing the game. If anyone has his problem run the cheat as admin or don't run csgo as admin.
